POST http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

{
  "firstName": "shanti",
  "lastName": "thapa",
  "email": "shantithapa2018@gmail.com",
  "password": "test123",
  "avatar":"imagelink1", 
  "addressCreateDTO": {
    "houseNumber": "10",
    "street": "katu",
    "postCode": "11223",
    "city": "Helsinki",
    "country": "Finland"
  }
}

###
POST http://localhost:5238/api/v1/auth HTTP/1.1
content-type: application/json

{
  "email": "admin@mail.com",
  "password": "admin123"
}

###
POST http://localhost:5238/api/v1/auth HTTP/1.1
content-type: application/json

{
  "email": "sunil@mail.com",
  "password": "sunil123"
}

###
GET http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

###
GET  http://localhost:5238/api/v1/users/0642c029-557e-4818-b288-2cf8d9d921df HTTP/1.1
content-type: application/json

###
PATCH   http://localhost:5238/api/v1/users/0fbf38f5-c7f4-436d-a506-81d777ecc300 HTTP/1.1
content-type: application/json

  {
  "id": "0fbf38f5-c7f4-436d-a506-81d777ecc300",
  "firstName": "suniiiil",
  "lastName": "karki",
  "email": "sunilkarki2019@gmail.com",
  "avatar": "string",
  "role": "Admin",
  "addressUpdateDTO": {
    "id": "9dcef977-1b5c-4a2c-8e5b-337f269a7ca2",
    "houseNumber": "10",
    "street": "katu",
    "postCode": "1122",
    "city": "Helsinki",
    "country": "Finland"
  }
}

###
DELETE  http://localhost:5238/api/v1/users/0642c029-557e-4818-b288-2cf8d9d921df HTTP/1.1
content-type: application/json