POST http://localhost:5238/api/v1/products HTTP/1.1
content-type: application/json

{
  "inventory": 25,
  "productLineId": "11bd0f6a-68c2-4004-a3da-2049e9eb1198",
  "productSizeId": "3f11df1b-3508-4344-8fa8-f95e3c6f4fdb"
}

###
GET http://localhost:5238/api/v1/products HTTP/1.1
content-type: application/json

###
GET http://localhost:5238/api/v1/products/80f34112-e69a-4bd6-bf58-271d888aa7ba HTTP/1.1
content-type: application/json

###
PATCH  http://localhost:5238/api/v1/products/e30b2333-6197-4955-adff-63db6beb6b45 HTTP/1.1
content-type: application/json

{
  "id":"e30b2333-6197-4955-adff-63db6beb6b45",
  "inventory": 35,
  "productLineId": "11bd0f6a-68c2-4004-a3da-2049e9eb1198",
  "productSizeId": "3f11df1b-3508-4344-8fa8-f95e3c6f4fdb"
}

######
DELETE  http://localhost:5238/api/v1/products/80f34112-e69a-4bd6-bf58-271d888aa7ba HTTP/1.1
content-type: application/json
