POST http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

{
  "firstName": "sunil",
  "lastName": "karki",
  "email": "sunil@mail.com",
  "role":"Customer",
  "password": "test123",
  "avatar":"imagelink1"
}

###
POST http://localhost:5238/api/v1/auth HTTP/1.1
content-type: application/json

{
  "email": "string",
  "password": "test123"
}

###
GET http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMDY5ZDZkNC00ODQxLTQwM2MtOTZkYi01YjJiN2E4OTQwY2YiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDI1ODc4NDAsImV4cCI6MTcwMjc2MDY0MCwiaWF0IjoxNzAyNTg3ODQwLCJpc3MiOiJTdW5pbCIsImF1ZCI6IlN1bmlsRUNvbW1lcmNlIn0.lxQFBQMUGiLvYLKlT0LOyqDcHgD9IWo9Z9Inwwb1cpg