POST http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

{
  "firstName": "sun",
  "lastName": "karki",
  "email": "sun@mail.com",
  "role":"Customer",
  "password": "test123",
  "avatar":"imagelink1"
}

###
POST http://localhost:5238/api/v1/auth HTTP/1.1
content-type: application/json

{
  "email": "sunil@mail.com",
  "password": "test123"
}

###
GET http://localhost:5238/api/v1/users HTTP/1.1
content-type: application/json

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2NjliYjc5ZS1mZmNkLTRkMWYtOGYzZC1lYWY3YTkzM2UxNDciLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE3MDI2Mjc1NTQsImV4cCI6MTcwMjgwMDM1NCwiaWF0IjoxNzAyNjI3NTU0LCJpc3MiOiJTdW5pbCIsImF1ZCI6IlN1bmlsRUNvbW1lcmNlIn0.ZLV-tDuIfObkBt0XhQ_5H5DbyRNzkCYNPcy4CQGROFY